package com.vardash.mafimushkil

object Routes {
    const val Splash = "splash"
    const val Welcome = "welcome"
    const val Onboarding = "onboarding"
    const val Home = "home"
    const val Services = "services"
    const val Orders = "orders"
    const val Promotions = "promotions"
    const val Notifications = "notifications"
    const val Categories = "categories"
    const val PlaceOrder = "place_order"
    const val SelectLocation = "select_location"
    const val ChooseOnMap = "choose_on_map"
    const val Details = "details"
    const val AddPhoto = "add_photo"
    const val OrderConfirmed = "order_confirmed"
    const val OrderDetail = "order_detail"
    const val Payments = "payments"
    const val PhoneVerification = "phone_verification"
    const val OtpVerification = "otp_verification"
    const val UpdateOtp = "update_otp"
    const val MyProfile = "my_profile"
    const val EditPhoto = "edit_photo"
    const val EditName = "edit_name"
    const val EditEmail = "edit_email"
    const val UpdatePhone = "update_phone"
    const val EditGender = "edit_gender"
    const val ContactUs = "contact_us"
    const val BecomeWorker = "become_worker"
    const val WorkerForm = "worker_form"
    const val RegisterCompany = "register_company"
    const val CompanyForm = "company_form"
    const val ServiceOrderDetail = "service_order_detail"
    const val ServiceOrderMap = "service_order_map"
    const val RevokeRegistration = "revoke_registration"

    fun categories(mode: String = "fresh"): String = "$Categories?mode=$mode"
    fun placeOrder(categoryId: String, categoryName: String, iconName: String = "cleaning"): String =
        "$PlaceOrder?categoryId=$categoryId&categoryName=$categoryName&iconName=$iconName"
    fun details(initialDetails: String = ""): String = "$Details?initialDetails=$initialDetails"
    fun orders(tab: Int = 0, focusOrderId: String = ""): String = "$Orders?tab=$tab&focusOrderId=$focusOrderId"
    fun orderDetail(orderId: String): String = "$OrderDetail/$orderId"
    fun serviceOrderDetail(orderId: String): String = "$ServiceOrderDetail/$orderId"
    fun serviceOrderMap(orderId: String): String = "$ServiceOrderMap/$orderId"
    fun payments(orderId: String): String = "$Payments/$orderId"
    fun otpVerification(phoneNumber: String): String = "$OtpVerification/$phoneNumber"
    fun updateOtp(phoneNumber: String): String = "$UpdateOtp/$phoneNumber"
    fun revokeRegistration(target: String): String = "$RevokeRegistration/$target"
}
